import messaging from '@react-native-firebase/messaging';
import React, {useEffect} from 'react';
import {View} from 'react-native';
import {Notifications} from 'react-native-notifications';
import {Button} from 'react-native-paper';
import STText from '../../components/STComponents/STText';

export default function PodCastScreen() {
  useEffect(() => {
    const getTokenDevice = async () => {
      await messaging().registerDeviceForRemoteMessages();
      const tokenDevice = await messaging().getToken();
      console.log('tokenDevice', tokenDevice);
    };
    getTokenDevice();
  }, []);

  const createNotification = async () => {
    Notifications.postLocalNotification({
      title: 'Local notification',
      body: 'This notification was generated by the app!',
      extra: 'data',
    });
  };
  return (
    <View className="flex items-center justify-center h-60">
      <STText font="medium" className="text-2xl text-black">
        Đang phát triển thêm...
      </STText>
      <Button mode="contained" onPress={() => createNotification()}>
        Button
      </Button>
    </View>
  );
}
