import React, {useEffect} from 'react';
import {LogBox} from 'react-native';
import 'react-native-gesture-handler';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {Provider as PaperProvider} from 'react-native-paper';
import SplashScreen from 'react-native-splash-screen';
import {Provider as StoreProvider} from 'react-redux';
import {TailwindProvider} from 'tailwindcss-react-native';
import store from './helpers/Redux/store';
import Navigation from './navigation';
import theme from './theme';
import {Notifications} from 'react-native-notifications';

export default function App() {
  useEffect(() => {
    Notifications.registerRemoteNotifications();

    Notifications.events().registerNotificationReceivedForeground(
      (notification, completion) => {
        console.log(
          `Notification received in foreground: ${notification.title} : ${notification.body}`,
        );
        completion({alert: false, sound: false, badge: false});
      },
    );

    Notifications.events().registerNotificationOpened(
      (notification, completion) => {
        console.log(`Notification opened: ${notification.payload}`);
        completion();
      },
    );

    Notifications.postLocalNotification({
      title: 'Local notification',
      body: 'This notification was generated by the app!',
      extra: 'data',
    });
  }, []);
  useEffect(() => {
    SplashScreen.hide();
  }, []);
  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <StoreProvider store={store}>
        <TailwindProvider>
          <PaperProvider theme={theme}>
            <Navigation />
          </PaperProvider>
        </TailwindProvider>
      </StoreProvider>
    </GestureHandlerRootView>
  );
}
LogBox.ignoreAllLogs();
